---
- name: Include vars of from config.yml
  hosts: master, workers
  tasks:
  - name:
    ansible.builtin.include_vars:
      file: config.yml
      name: rollout_config


- name: Master Node uninstall
  hosts: master
  gather_facts: no
  
  tasks:
    - name: Uninstall k3s in Master Node
      shell: |
              /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true
      become: true
      become_method: sudo

- name: Uninstall K3s on Worker nodes
  hosts: workers
  
  tasks: 
    - name: Uinstalling K3s agents
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
      become: true
      become_method: sudo


- name: disable swap
  hosts: master, workers
  gather_facts: true

  tasks:
    - name: Enable swap on all nodes permanently and sets swap-size to raspbian-default-value (20) (active at next reboot)
      lineinfile: 
        path: /etc/dphys-swapfile
        regexp: '^CONF_SWAPSIZE=.*'
        line: 'CONF_SWAPSIZE={{rollout_config.raspbian_swap_size }}'
      become: true
      become_method: sudo

    - name: Enable swap imidiatly
      shell: swapon -a
      become: true
      become_method: sudo

- name: Check cgroup configuration
  hosts: master, workers
  gather_facts: no

  tasks:
    - name: remove cgroup definition to setup raspberry-default
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: "cgroup_enable=cpu_set cgroup_memory=1 cgroup_enable=memory"
        replace: ''
      become: true
      become_method: sudo

    - name: Execute if not existing, reboot, and wait for {{ rollout_config.reboottime }} seconds
      shell: sleep 5 && shutdown -r now "Ansible Rebooting after cgroup configuration"
      async: 0
      poll: 0
      ignore_unreachable: true
      become: true
      become_method: sudo

    - name: Waiting for server to come back
      wait_for_connection:
        delay: "{{ rollout_config.reboottime }}"
