---
- name: Install NFS server on master nodes and NFS client on worker nodes
  hosts: all
  become: yes

  tasks:
    - name: Install NFS server on master nodes
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes
      when: "'master' in group_names"

    - name: Install NFS client on worker nodes
      apt:
        name: nfs-common
        state: present
        update_cache: yes
      when: "'workers' in group_names"
